### ISSUE TITLE
coroutine RmqCommunicator closing closed Channel

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/kiwipy#23] opened 2019-04-17 12:16 UTC
In test `test/rmq/test_rmq_thread_communicator.py::TestRmqThreadCommunicator::test_rpc_nested_futures`

```python
RESULT = "You've reached the bottom of the rabbit hole my friend"  # pylint: disable=invalid-name

def rpc_subscriber(_comm, _msg):
    future1 = kiwipy.Future()
    future2 = kiwipy.Future()
    future1.set_result(future2)
    future2.set_result(RESULT)
    return future1

# Check we're getting messages
self.communicator.add_rpc_subscriber(rpc_subscriber, rpc_subscriber.__name__)
future1 = self.communicator.rpc_send(rpc_subscriber.__name__, None).result(timeout=self.WAIT_TIMEOUT)
self.assertIsInstance(future1, kiwipy.Future)

# future2 = future1.result(timeout=self.WAIT_TIMEOUT)
# self.assertIsInstance(future2, kiwipy.Future)
#
# result = future2.result(timeout=self.WAIT_TIMEOUT)
# self.assertEqual(RESULT, result)
```

When comment last 5 lines.
If future1 is not yielded, I always get error `ChannelWrongStateError: Channel is closing.` when destroy the communitor.

I find this is caused when disconnecting `RmqSubscriber`.
Maybe problem caused by class:RmqSubscriber;method:disconnect()?

**Comment by muhrin** [comment] 2020-04-22 07:26
Hi Jason,

Sorry to pick this up so late!  I've had a look and I can't reproduce this bug.  We've changed the code a bit since last year so it's possible that it has been fixed.

I'm closing this issue as "can't reprocuce" but if you see if please do reopen it.

**Closed by muhrin** 2020-04-22 07:26 UTC
Labels: can't reproduce
